# Generated by Django 6.0.7 on 2026-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['created_at', 'title']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['start_date', 'title']},
        ),
        migrations.RenameField(
            model_name='grocerylist',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='personallist',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach'), ('sky', 'Sky')], default='yellow', max_length=20),
        ),
        migrations.AddField(
            model_name='personallist',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach'), ('sky', 'Sky')], default='yellow', max_length=20),
        ),
        migrations.AddField(
            model_name='tripnote',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach'), ('sky', 'Sky')], default='yellow', max_length=20),
        ),
    ]
