# Generated by Django 6.0.7 on 2026-07-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude in decimal degrees, for example 47.250376', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude in decimal degrees, for example -79.890442', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable place name, trailhead, campsite, or region.', max_length=200),
        ),
    ]
