# Generated by Django 6.0.7 on 2026-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_grocerylist_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach')], default='yellow', max_length=20),
        ),
        migrations.AlterField(
            model_name='personallist',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach')], default='yellow', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripnote',
            name='panel_color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('peach', 'Peach')], default='yellow', max_length=20),
        ),
    ]
